slam:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # Localization parameters
    localization_rate: 50.0
    fine_localization_rate: 0.0
    map_to_odom_rate: 200.0

    map_to_odom_correction: True

    isam_relinearize_skip: 1
    isam_relinearize_threshold: 0.0001

    init_prior_noise: [0.001, 0.001, 0.001]
    marginal_prior_noise: [0.002, 0.002, 0.002]
    observation_noise: [0.02, 0.02]
    odometry_noise: [0.02, 0.02, 0.005]

    window_size: 20
    # window_size: -1
    lag: 3

    use_fixed_marginal: True

    min_pose_displacement: 0.05
    min_pose_theta_displacement: 10.0

    # data_association_mode: "nn"
    # data_association_mode: "flann"
    data_association_mode: "pda"

    use_all_landmarks: False

    data_association_distance: 0.2
    mahalanobis_dist_threshold: 2.0



    # Mapping parameters
    mapping_rate: 0.5
    
    map_resolution: 0.05
    map_initial_width: 100.0
    map_initial_height: 100.0

    map_initial_value: -1

    use_rays_over_range_max: True

    free_belief: 0.38
    occupied_belief: 0.80
    distance_belief_factor: 0.03

    apply_threshold: True
    occupied_threshold: 0.70
    free_threshold: 0.30

    override_active_hit_points: True

    noise_model_radius: 0.07
    noise_model_std_dev: 0.02

    frontier_cells_detection_mode: "ewfd"




    # Frontier detection parameters
    frontier_detection_rate: 0.2

    epsilon: 0.5
    min_points: 3

    min_frontier_size: 20

    use_sim_time: False